project:
  type: website
  output-dir: docs

website:
  title: "Kate Nelson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - papers.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full



